
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/public/home/zhangxin/dcu/miniconda3/envs/snsc-dcu-qcu/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 3.10.0-1160.el7.x86_64 - x86_64
