#ifndef _INCLUDE_H
#define _INCLUDE_H
#pragma once
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuComplex.h>
// #include <cublas_api.h>
#include <cublas_v2.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_runtime_api.h>
#include <curand.h>
#include <curand_kernel.h>
#include <functional>
#include <iostream>
#include <library_types.h>
#include <memory>
#include <mpi.h>
#include <nccl.h>
#include <random>
#include <stdexcept>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <unistd.h>
#include <vector>
#endif